X_STEP, Y_STEP = 1, 1
# To be further discussed
HEIGHT, WIDTH = 22, 44
LEFT_BOUND = 1 
RIGHT_BOUND = WIDTH-2
UP_BOUND = 0
DOWN_BOUND = HEIGHT-1

# Direction id
LEFT = 2
RIGHT = 3

# Obstacle
INITIAL_OBSTACLE_SPEED = 0.5
OBSTACLE_GENERATION_INTERVAL = 3
OBSTACLE_LIFE = 2

# Acceleration
ACCELERATION = 0.8
ACCELERATION_INTERVAL = 30

# Bullet
BULLET_SPEED = 0.5
BULLET_GENERATION_INTERVAL = 0.5